# Generated by Django 5.1.6 on 2025-05-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classmate',
        ),
        migrations.RemoveField(
            model_name='program',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='program',
            name='leader',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
