# Generated by Django 5.1.6 on 2025-05-23 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0004_figurines_mugs_soda_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='figurines',
            name='image',
            field=models.ImageField(default=255, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mugs',
            name='image',
            field=models.ImageField(default=255, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soda',
            name='image',
            field=models.ImageField(default=255, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toys',
            name='image',
            field=models.ImageField(default=255, upload_to='images/'),
            preserve_default=False,
        ),
    ]
