# Generated by Django 5.1.6 on 2025-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0005_figurines_image_mugs_image_soda_image_toys_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='figurines',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mugs',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='soda',
            name='image',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='toys',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
