# Generated by Django 5.1.6 on 2025-05-24 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('courses', models.TextField(help_text='Что я буду изучать')),
                ('skills', models.TextField(help_text='Чему я научусь')),
                ('advantages', models.TextField()),
                ('prospects', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProgramManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('AR', 'Академический руководитель'), ('M', 'Менеджер')], max_length=2)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSite.educationalprogram')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('photo', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.CharField(max_length=100000)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='program',
            name='leader',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AlterField(
            model_name='classmate',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='classmate',
            name='program',
            field=models.ForeignKey(default=2555, on_delete=django.db.models.deletion.CASCADE, to='WebSite.educationalprogram'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
